version: '3.8'

services:
  # Java API Service
  backend-service:
    image: ghcr.io/medotarek73/java-microservice-api:${IMAGE_TAG:-latest}
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_HTTP_PORT=8080
      - QUARKUS_HTTP_HOST=0.0.0.0
    networks:
      - app-network

  # Next.js Frontend Service
  frontend-application:
    image: ghcr.io/medotarek73/nextjs-monorepo:${IMAGE_TAG:-latest}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - API_URL=http://backend-service:8080
    depends_on:
      - backend-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  node_modules:
  maven_cache:
