apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-semibots-com
  namespace: default
spec:
  secretName: wildcard-semibots-com-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
  - "*.semibots.com"
  - "semibots.com"
